services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb # need this line?
    restart: always # look at other options
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
      - ./requirements/nginx/ssl:/etc/ssl/certs
    networks:
      - inception
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lbarry/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lbarry/data/wordpress
networks:
  inception:
    driver: bridge